# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            exmerica
tagline:          'Global Futurism'
description:      'Contemplations on society, technology, and the future'
url:              http://exmerica.github.io/

author:
  name:           'exmerica'
  url:            exmerica.github.io
  email:          'exmerica@protonmail.com'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/exmerica/exmerica.github.io
